
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Azure Static Website
        # You may pin to the exact commit or the version.
        # uses: tibor19/static-website-deploy@e937952c714a3751355a17896498418a9931ded5
        uses: tibor19/static-website-deploy@v1
        with:
          # Connection String of the Azure Storage Container
          connection-string: ${{ secrets.STORAGE_KEY }}
          # Name of the Blob Container Storage
          blob-container-name: $web # optional
          # Enabled static website
          enabled-static-website: true
          # Index file for the static website
          index-file: index.html
          # If the existing files should be removed before uploading the new files
          remove-existing-files: true # optional
